sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

before_install:
  - pwd
  - ls -l
  - cd SD-K9

install:
  - npm install

before_script:
  - cd SD-K9

script:
  - npm run test -- --watch=false --no-progress 

