sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

before_install:
  - cd SD-K9
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress 

