sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - cd SD-K9

install:
  - npm install

script:
  - xvfb-run npm run test -- --watch=false --no-progress 

