sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

before_cache:
  - cd ./sd-k9

cache:
  directories:
    - node_modules

before_install:
  - cd ./sd-k9

install:
  - npm install

before_script:
  - cd ./sd-k9
  
script:
  - npm run test -- --watch=false --no-progress 

