sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

before_install:
  - cd SD-K9
  - export DISPLAY=:99.0

install:
  - npm install

script:
  - xvfb-run npm run test -- --watch=false --no-progress 

